#!/usr/bin/env python

import optparse
import os
import random
import shutil
import sys

alpha = 'abcdefghijklmnopqrstuvwxyz0123456789'

def GetRoot():
	return os.path.abspath(os.path.dirname(__file__))

def GenName(root):
	name = ''.join([alpha[random.randint(0, len(alpha) - 1)] for i in range(3)])
	if not os.path.exists(os.path.join(root, name)):
		return name
	return GenName(root)

def Rewrite(dir, old_name, new_name):
	# rename directories first
	ops = []
	for root, dirs, _ in os.walk(dir):
		for d in dirs:
			if d.find(old_name) >= 0:
				ops.append((
					os.path.join(root, d),
					os.path.join(root, d.replace(old_name, new_name))
				))
	for src, dst in ops:
		shutil.move(src, dst)

	# rename files next
	ops = []
	for root, _, files in os.walk(dir):
		for f in files:
			if f.find(old_name) >= 0:
				ops.append((
					os.path.join(root, f),
					os.path.join(root, f.replace(old_name, new_name))
				))
	for src, dst in ops:
		shutil.move(src, dst)

	# rewrite content last
	for root, _, files in os.walk(dir):
		for f in files:
			dst = os.path.join(root, f)
			with open(dst, 'r') as r:
				data = r.read()
				updt = data.replace(old_name, new_name)
				if data != updt:
					with open(dst, 'w') as w:
						w.write(updt)

def main():
	parser = optparse.OptionParser()
	parser.add_option('-n', '--name', dest='name', default=None, help='')
	opts, args = parser.parse_args()

	root = GetRoot()
	tplt = os.path.join(root, 'emptyExample')

	name = opts.name
	if name is None:
		name = GenName(root)

	dest = os.path.join(root, name)

	shutil.copytree(tplt, dest)

	Rewrite(dest, 'emptyExample', name)

	return 0

if __name__ == '__main__':
	sys.exit(main())
